operator:
  auth:
    createSigningSecret: true
    signingSecretName: fluidbg-operator-auth
    signingSecretValue: dev-signing-key-change-me

builtinPlugins:
  rabbitmq:
    manager:
      enabled: true
      amqpUrl: amqp://fluidbg:fluidbg@rabbitmq.fluidbg-demo:5672/%2f
      managementUrl: http://rabbitmq.fluidbg-demo:15672
      managementAllowInsecure: true
      managementUsername: fluidbg
      managementPassword: fluidbg
      managementVhost: /
  nats:
    manager:
      enabled: true
      url: nats://nats.fluidbg-demo:4222
