apiVersion: v2
name: fluidbg-operator
description: FluidBG Kubernetes operator and built-in inception plugin definitions
type: application
version: 0.6.2
appVersion: 0.6.2
kubeVersion: ">=1.30.0-0"
keywords:
  - blue-green
  - kubernetes-operator
  - progressive-delivery
  - rabbitmq
  - nats
  - http
home: https://github.com/dlahmad/fluidbgoperator
sources:
  - https://github.com/dlahmad/fluidbgoperator
maintainers:
  - name: FluidBG maintainers
