nameOverride: ""
fullnameOverride: ""

operator:
  replicaCount: 1
  image:
    repository: ghcr.io/dlahmad/fbg-operator
    tag: 0.1.0
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  podAnnotations: {}
  podLabels: {}
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 256Mi
  rustLog: info
  api:
    port: 8090
  nodeSelector: {}
  tolerations: []
  affinity: {}
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
    capabilities:
      drop: ["ALL"]
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

service:
  type: ClusterIP
  port: 8090

rbac:
  create: true

serviceAccount:
  create: true
  name: ""
  annotations: {}

builtinPlugins:
  install: true
  # InceptionPlugin resources are namespaced and are resolved in the same
  # namespace as the BlueGreenDeployment. Leave empty to install into the Helm
  # release namespace. Add application namespaces that should use the built-ins.
  namespaces: []
  http:
    enabled: true
    image:
      repository: ghcr.io/dlahmad/fbg-plugin-http
      tag: 0.1.0
  rabbitmq:
    enabled: true
    image:
      repository: ghcr.io/dlahmad/fbg-plugin-rabbitmq
      tag: 0.1.0
