apiVersion: v1
kind: Service
metadata:
  name: fluidbg-operator
  labels:
    {{- include "fluidbg.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "fluidbg.selectorLabels" . | nindent 4 }}

